### ISSUE TITLE
Unable to install - bash: automata: command not found

### ISSUE THREAD

**Issue by ztxtz** [emrgnt-cmplxty/automata#427] opened 2023-08-04 11:34 UTC
Following installation instructions in the README results in `bash: automata: command not found` when running `automata configure`

Using docker jumps into a python console:

```
@ztxtz ➜ /workspaces/automata (main) $ docker run --name automata_container -it --rm -e OPENAI_API_KEY=sk-xxxx -e GITHUB_API_KEY=xxxxx ghcr.io/emrgnt-cmplxty/automata:latest
Python 3.10.12 (main, Jun 13 2023, 15:57:17) [GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

How to replicate:

1) Open Github codespace on the main branch
2) Follow installations instructions from README

```
# Initialize git submodules
git submodule update --init

# Install poetry and the project
pip3 install poetry && poetry install

# Configure the environment and setup files
automata configure
```

**Comment by NolanTrem** [comment] 2023-08-04 14:41
Hey @ztxtz, thanks for checking out the project!

I was able to replicate and it seems that this is because poetry installs in an isolated environment, so Python doesn't know where to look for the automata installation. If you run `poetry run automata configure` you'll see the correct and expected behavior.

I'll update the docs to reflect this—thanks again and let me know if this works for you 😁

**Comment by NolanTrem** [comment] 2023-08-04 14:49
Closing this for now, but please feel free to reopen if this issue isn't resolved.

**Closed by NolanTrem** 2023-08-04 14:49 UTC
